workflows:
  version: 2
  main:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master


version: 2
jobs:
  build:
    docker:
      - image: cibuilds/hugo:0.33
    steps:
      - checkout
      - run:
          name: "Build Website with Hugo"
          command: HUGO_ENV=production hugo -v
      - run:
          name: "Test Website"
          command: cd public; htmlproofer . --allow-hash-href --check-html --empty-alt-ignore
      - persist_to_workspace:
          root: .
          paths:
            - public

  deploy:
    docker:
      - image: cibuilds/hugo:0.33
    steps:
      - attach_workspace:
          at: .
      - run: echo "Deploy docs here."
